spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lyedu?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: lyedu123456

logging:
  level:
    com.lyedu: debug
